[global]
mraauthor=["jotego"]

[features]
beta = true

[parse]
sourcefile="dec0.cpp"

[buttons]
core=5

[rbf]
name="jtcop"
dev = [
    { dev="i8751",   rbf="jtninja" }
]

[dipsw]
delete = [ "Unused", "Unknown" ]

[ROM]
regions = [
    { name="maincpu",       width=16, reverse=true },
    { name="audiocpu",      start=$BA1_START, No_offset=true  },
    { name="oki",           start=$PCM_START },
    { name="gfx1",          start=$BA2_START, width=16, No_offset=true },
    { name="gfx2",          start=$GFX2_START,width=16, No_offset=true, sort_byext=true, sort_alpha=true },
    { name="gfx3",          start=$GFX3_START,width=16, No_offset=true, sort_byext=true, sort_alpha=true  },
    { name="gfx4",          start=$BA3_START },
    { name="sub",           start=$MCU_START },
    { name="mcu",           start=$MCU_START },
    { name="proms",         start=$PROM_START },
    { name="plds",          skip=true         }
]

order = [
    "maincpu", "audiocpu", "oki",
    "gfx1", "gfx2", "gfx3", "gfx4", "mcu", "sub", "proms"
]

splits = [
    { machine="baddudes", region="gfx1", offset=0x4000, min_len=0x10000 },
    { machine="baddudes", region="gfx3", offset=0x8000, min_len=0x20000 },
    { machine="secretag", region="gfx1", offset=0x4000, min_len=0x10000 },
    { machine="birdtry",  region="gfx1", offset=0x4000, min_len=0x10000 }
]

blanks = [
    { machine="baddudes", region="gfx2", offset=0x20000, len=0x20000 }
]